### ISSUE TITLE
Add image to Page Top

### ISSUE THREAD

**Issue by mangawill** [GavickPro/Music-Free-Responsive-Joomla-Template#136]
Hi is there a way i can add an image to the page top next to my logo?

**Comment by bkrztuk** [comment]
Only by modifying file **template/layout/blocks/logo.php***, there you can includ your own `<img>` tag

**Comment by EmanuelFromFlorence** [comment]
I'm actually doing the same.

extension,template manager,styles,gk music free ,options,features
Logo Type Image
select a logo type image and then save

this has worked for me except the right margin i have on Tablet 
and for whom i asked help in order to have a full wide image from right to left
on the top of the page
where to modify the values

body #gkPageTop, body #gkToolbar, #gkFooter {
padding-left: 0px;
padding-right: 0px;
margin-left: 0px!important;

on my site on /:44 ..but i'm not able to locate in my css ..

**Comment by bkrztuk** [comment]
Logo dimensions are always included in template.css file, please just use Firebug to find proper file and rule to modify.
