### ISSUE TITLE
auth improvements / idea : login module

### ISSUE THREAD

**Issue by ghost** [GavickPro/Music-Free-Responsive-Joomla-Template#23]
gk_login_module + OAuth 2.0

**Comment by dziudek** [comment]
Maybe in the future - currently there is too much problems with OAuth implementation in Joomla!.

**Comment by keshavpareek** [comment]
where to find the gk_login_module. unable to show the sign in link at frontend

**Comment by dziudek** [comment]
It is a standard mod_login module which should be loaded on the "login" module position.

**Comment by keshavpareek** [comment]
Hi i have applied as mention by you but again there is a prob
If i use ?tp=1 then it is visible otherwise not on home page
and
Now it is visible on all other links except home page( if home has /index.php it is visible) and getting started page of default joomla content

i have configured it as show on all pages

**Comment by dziudek** [comment]
Could you provide me your admin access and URL to your website to dziudek[at]gavick[dot]com ?

**Comment by keshavpareek** [comment]
Thanks dear just got fixed it now working fine might be any caching issue or else but now got it working

**Comment by dziudek** [comment]
OK :) So I'm closing this issue.
