### ISSUE TITLE
Mobile and Tablet suffixes not working 

### ISSUE THREAD

**Issue by losisin** [GavickPro/Music-Free-Responsive-Joomla-Template#59]
I'm having trouble using the module suffix for mobile and tablet. When I apply ' notablet nomobile', nothing happens. I've double check the space before each suffix . The same thing happens with onlymobile onlytablet. Any help will be very appreciated.
Thanx

**Comment by dziudek** [comment]
Hi,

Did you used these suffixes with the space at the beginning? In example " onlytablet" ?

**Comment by losisin** [comment]
Yes. I've double checked. At first I thought those suffixes apply only to sidebar main module positions, and not toolbar, social etc..., but 
The thing is that when you apply ' no tablet nomobile', the module disappears from every view (desktop full screen and resized, mobile phone and so on) in every module position

**Comment by dziudek** [comment]
Please apply these changes:

https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/593454f27fc7e3616b33d0d2a7ba34b9a1bde5a6

https://github.com/GavickPro/Music-Free-Responsive-Joomla-Template/commit/92c88713374831571ccfbd019564fe3c3877ccca

and then please use the onlydesktop suffix instead of nomobile + notablet.

**Comment by losisin** [comment]
Excellent. Thank you for the ' onlydesktop', much better and simple solution
